version: '3.8'

services:
  mssql-server:
    image: "mcr.microsoft.com/mssql/server:2019-latest"
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_PID: Developer
      MSSQL_SA_PASSWORD: Admin123!
    ports:
      - "1433:1433"
    volumes:
      - "mssql-server:/var/opt/mssql"

  # adminer:
  #   image: adminer:4.8.1
  #   ports:
  #     - "1433:8080"
  #   environment:
  #     TZ: Europe/Rome
  #     ADMINER_DEFAULT_SERVER: mssql-server

  # Servizio Zookeeper (necessario per Kafka)
  # zookeeper:
  #   container_name: zookeeper
  #   image: 'bitnami/zookeeper:3.9.0'
  #   ports:
  #     - "2181:2181"
  #   environment:
  #     - ALLOW_ANONYMOUS_LOGIN=yes

  # Servizio Kafka (commentato per disabilitare Kafka)
  # kafka:
  #   container_name: kafka
  #   image: 'bitnami/kafka:3.1.0'
  #   ports:
  #     - "9092:9092"
  #   environment:
  #     - KAFKA_BROKER_ID=1
  #     - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092
  #     - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
  #     - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
  #     - ALLOW_PLAINTEXT_LISTENER=yes
  #     - KAFKA_AUTO_CREATE_TOPICS_ENABLE=true
  #   depends_on:
  #     - zookeeper

  # Servizio OrderService
  orderservice:
    build:
      context: ./OrderService
      dockerfile: OrderService.Api/Dockerfile
    container_name: orderservice
    depends_on:
      - mssql-server  # 
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      # - ConnectionStrings__OrderDb=Server=host.docker.internal,1433;Database=OrderDb;User Id=sa;Password=Admin123!;TrustServerCertificate=True;Encrypt=False;
    ports:
      - "5000:5000"

  # Servizio InventoryService
  inventoryservice:
    build:
      context: ./InventoryService
      dockerfile: InventoryService.Api/Dockerfile
    container_name: inventoryservice
    depends_on:
      - mssql-server 
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      # - ConnectionStrings__InventoryDb=Server=inventoryservice-db,1433;Database=InventoryDb;User Id=sa;Password=Admin123!;TrustServerCertificate=True;Encrypt=False;
    ports:
      - "5001:5001"

volumes:
  mssql-server:
