
services:
  # Database per OrderService
  orderservice-db:
    image: "mcr.microsoft.com/mssql/server:2019-latest"
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_PID: Developer
      MSSQL_SA_PASSWORD: Your_password123
    ports:
      - 1433:1433
    volumes:
      - "orderservice-db:/var/opt/mssql"

  # Database per InventoryService
  inventoryservice-db:
    image: "mcr.microsoft.com/mssql/server:2019-latest"
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_PID: Developer
      MSSQL_SA_PASSWORD: Your_password123
    ports:
      - 1434:1433
    volumes:
      - "inventoryservice-db:/var/opt/mssql"

  # Kafka e Zookeeper
  zookeeper:
    container_name: zookeeper
    image: 'bitnami/zookeeper:3.9.0'
    ports:
      - '2181:2181'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes

  kafka:
    container_name: kafka
    image: 'bitnami/kafka:3.1.0'
    ports:
      - '9092:9092'
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_AUTO_CREATE_TOPICS_ENABLE=true
    depends_on:
      - zookeeper

  # OrderService
  orderservice:
    build:
      context: ./OrderService
      dockerfile: OrderService.Api/Dockerfile
    container_name: orderservice
    depends_on:
      - orderservice-db
      - kafka
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__OrderDb=Server=orderservice-db;Database=OrderDb;User=sa;Password=Your_password123;
      - Kafka__BootstrapServers=kafka:9092
    ports:
      - "5000:5000"

  # InventoryService
  inventoryservice:
    build:
      context: ./InventoryService
      dockerfile: InventoryService.Api/Dockerfile
    container_name: inventoryservice
    depends_on:
      - inventoryservice-db
      - kafka
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__InventoryDb=Server=inventoryservice-db;Database=InventoryDb;User=sa;Password=Your_password123;
      - Kafka__BootstrapServers=kafka:9092
    ports:
      - "5001:5001"

volumes:
  orderservice-db:
  inventoryservice-db:
