version: '3.8'

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: sqlserver
    ports:
      - "1433:1433"
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "YourPassword123!"
    networks:
      - app-network
      

  orderservice:
    build:
      context: .
      dockerfile: OrderService.Api/Dockerfile # Dockerfile della tua applicazione
    container_name: orderservice
    ports:
      - "5000:5000" # Esponi l'API sulla porta 5000
    environment:
      ConnectionStrings__OrderDb: "Server=sqlserver,1433;Database=OrderDb;User Id=sa;Password=YourPassword123!" # Stringa di connessione per il DB
    depends_on:
      - sqlserver
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
